apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  restaurantdb_url: jdbc:mysql://mysql-db-instance2.c14wwkio2s6j.eu-west-2.rds.amazonaws.com:3306/restaurantdb?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=true
  foodcataloguedb_url: jdbc:mysql://mysql-db-instance2.c14wwkio2s6j.eu-west-2.rds.amazonaws.com:3306/foodcataloguedb?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=true
  userdb_url: jdbc:mysql://mysql-db-instance2.c14wwkio2s6j.eu-west-2.rds.amazonaws.com:3306/userdb?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=true
  orderdb_url: mongodb+srv://admin:Policy001@atlas-cluster2.v9v1v7g.mongodb.net/?retryWrites=true&w=majority
  eureka_service_address: http://eureka-0.eureka-service:8761/eureka

  
  # restaurantdb: restaurantdb
  # mysql-server: mysql-service    # The name of mysql service
  # mysql-user-username: root
  # citizen_database_url: jdbc:mysql://mysql-service:3306/citizendb
  # foodcataloguedb_url: jdbc:mysql://mysql-service:3306/foodcataloguedb
  # userdb_url: jdbc:mysql://mysql-service:3306/userdb
  # foodcataloguedb: foodcataloguedb
  # userdb: userdb
  